name: "Terraform Azure Resource Group"
on:
  push:
    branches:
      - main  # Trigger on push to main branch

permissions:
  id-token: write  # Required to fetch an OIDC token
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to Azure using Service Principal (via GitHub Secrets)
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        federated-token: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        allow-no-subscriptions: true

    # Step 4: Export USE_AZURE_AD environment variable
    - name: Set environment variable
      run: |
          echo "USE_AZURE_AD=true" >> $GITHUB_ENV
          echo "ARM_USE_MSI=true" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=2557041f-ab5b-4b08-806f-27b25d7d69ef" >> $GITHUB_ENV
    

   # - name: Login to Azure using Username and Password
    #  uses: azure/login@v1
     # with:
      #  username: ${{ secrets.AZURE_USERNAME }}  # Azure username (email address)
       # password: ${{ secrets.AZURE_PASSWORD }}  # Azure password    

    # Step 3: Set up Terraform (configure Terraform version)
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Initialize Terraform (in the terraform/ directory)
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Path to the folder containing your Terraform files

     # Step 5: Apply Terraform Configuration (in the terraform/ directory)
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Path to the folder containing your Terraform files
     
    # step 5 :Destroy resources created by terraform
    
    #- name: Terraform Destroy
     # run: terraform destroy -auto-approve
     # working-directory: ./terraform
