name: "Terraform Azure Resource Group"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Azure Cloud Shell with Terraform
    - name: Login to Azure using Cloud Shell
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Apply Terraform Configuration
    - name: Terraform Apply
      run: terraform apply -auto-approve
