name: Terraform Azure Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"  # Use the latest stable version or your desired version

      - name: Set up Azure CLI (for authentication)
        uses: azure/setup-azure-cli@latest
        with:
          azure-cli-version: latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
